/**
 * Rhythm desktop theme contribution, registered via THEMES_AREA so Rhythm's
 * palette shows up anywhere a built-in Hermes theme does (Cmd-K, Appearance
 * settings, /skin) without any per-surface wiring.
 *
 * GENERATED by generate.py from ../../theme/tokens.json. Do not hand-edit —
 * edit tokens.json and run:
 *   python3 plugins/rhythm/theme/generate.py --write
 */

export interface RhythmDesktopThemeColors {
  background: string
  foreground: string
  card: string
  cardForeground: string
  muted: string
  mutedForeground: string
  popover: string
  popoverForeground: string
  primary: string
  primaryForeground: string
  secondary: string
  secondaryForeground: string
  accent: string
  accentForeground: string
  border: string
  input: string
  ring: string
  midground: string
  destructive: string
  destructiveForeground: string
  sidebarBackground: string
  sidebarBorder: string
}

export interface RhythmDesktopTheme {
  name: string
  label: string
  description: string
  colors: RhythmDesktopThemeColors
  darkColors: RhythmDesktopThemeColors
}

export const rhythmDesktopTheme: RhythmDesktopTheme = {
  name: 'rhythm',
  label: 'Rhythm',
  description: 'Rhythm workspace colors',
  colors: {
    background: '#ECF6F2',
    foreground: '#03201D',
    card: '#F8FDFB',
    cardForeground: '#03201D',
    muted: '#D8EEE5',
    mutedForeground: '#19403A',
    popover: '#FFFFFF',
    popoverForeground: '#03201D',
    primary: '#007760',
    primaryForeground: '#F2FBF7',
    secondary: '#D8EEE5',
    secondaryForeground: '#03201D',
    accent: '#D8EEE5',
    accentForeground: '#03201D',
    border: '#C0D7D1',
    input: '#5D837B',
    ring: '#007760',
    midground: '#007760',
    destructive: '#AC1730',
    destructiveForeground: '#FFF6F6',
    sidebarBackground: '#D8EEE5',
    sidebarBorder: '#C0D7D1',
  },
  darkColors: {
    background: '#252727',
    foreground: '#DEDFDF',
    card: '#2B2E2D',
    cardForeground: '#DEDFDF',
    muted: '#323735',
    mutedForeground: '#BFC6C3',
    popover: '#363C39',
    popoverForeground: '#DEDFDF',
    primary: '#42C3A6',
    primaryForeground: '#010E0C',
    secondary: '#323735',
    secondaryForeground: '#DEDFDF',
    accent: '#363C39',
    accentForeground: '#DEDFDF',
    border: '#3E4542',
    input: '#697571',
    ring: '#42C3A6',
    midground: '#42C3A6',
    destructive: '#FF666F',
    destructiveForeground: '#140707',
    sidebarBackground: '#323735',
    sidebarBorder: '#3E4542',
  },
}

export default rhythmDesktopTheme
