/**
 * Rhythm desktop theme contribution, registered via THEMES_AREA so Rhythm's
 * palette shows up anywhere a built-in Hermes theme does (Cmd-K, Appearance
 * settings, /skin) without any per-surface wiring.
 *
 * GENERATED by generate.py from ../../theme/tokens.json. Do not hand-edit —
 * edit tokens.json and run:
 *   python3 plugins/rhythm/theme/generate.py --write
 */

export interface RhythmDesktopThemeColors {
  background: string
  foreground: string
  card: string
  cardForeground: string
  muted: string
  mutedForeground: string
  popover: string
  popoverForeground: string
  primary: string
  primaryForeground: string
  secondary: string
  secondaryForeground: string
  accent: string
  accentForeground: string
  border: string
  input: string
  ring: string
  midground: string
  destructive: string
  destructiveForeground: string
  sidebarBackground: string
  sidebarBorder: string
}

export interface RhythmDesktopTheme {
  name: string
  label: string
  description: string
  colors: RhythmDesktopThemeColors
  darkColors: RhythmDesktopThemeColors
}

export const rhythmDesktopTheme: RhythmDesktopTheme = {
  name: 'rhythm',
  label: 'Rhythm',
  description: 'Rhythm workspace colors',
  colors: {
    background: '#FFFFFF',
    foreground: '#111827',
    card: '#FFFFFF',
    cardForeground: '#111827',
    muted: '#F3F4F6',
    mutedForeground: '#6B7280',
    popover: '#FFFFFF',
    popoverForeground: '#111827',
    primary: '#4E69F2',
    primaryForeground: '#FFFFFF',
    secondary: '#F8F9FA',
    secondaryForeground: '#111827',
    accent: '#EEF1FF',
    accentForeground: '#263CA8',
    border: '#E5E7EB',
    input: '#E5E7EB',
    ring: '#4F6AF5',
    midground: '#4F6AF5',
    destructive: '#DC2626',
    destructiveForeground: '#FFFFFF',
    sidebarBackground: '#F8F9FA',
    sidebarBorder: '#E5E7EB',
  },
  darkColors: {
    background: '#111827',
    foreground: '#F9FAFB',
    card: '#1F2937',
    cardForeground: '#F9FAFB',
    muted: '#273449',
    mutedForeground: '#D1D5DB',
    popover: '#1F2937',
    popoverForeground: '#F9FAFB',
    primary: '#8EA0FF',
    primaryForeground: '#111827',
    secondary: '#273449',
    secondaryForeground: '#F9FAFB',
    accent: '#283667',
    accentForeground: '#E0E7FF',
    border: '#374151',
    input: '#4B5563',
    ring: '#8EA0FF',
    midground: '#8EA0FF',
    destructive: '#F87171',
    destructiveForeground: '#111827',
    sidebarBackground: '#1F2937',
    sidebarBorder: '#374151',
  },
}

export default rhythmDesktopTheme
